name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: api-test-376019
  SERVICE: default
  REGION: southamerica-east1

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
    - id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/627344324507/locations/global/workloadIdentityPools/github-pool
        service_account: deploy@api-test-376019.iam.gserviceaccount.com

    - id: deploy
      uses: google-github-actions/deploy-appengine@v1